  
Trainer:
  accelerator: gpu
  devices: auto
  max_epochs: 5
  val_check_interval: 100
  accumulate_grad_batches: 2
  gradient_clip_val: 1.0
  log_every_n_steps: 50

Strategy:
  DDPStrategy:
    find_unused_parameters: true

Callbacks:
  LearningRateMonitor:
    logging_interval: step

  EarlyStopping:
    monitor: val_acc
    patience: 10
    mode: max

  ModelCheckpoint:
    monitor: val_acc
    save_top_k: 5
    mode: max
    dirpath: ./checkpoints/${now:%Y-%m-%d}/${now:%H-%M-%S}


Profiler:
  SimpleProfiler:
