hydra:
  run:
    dir: ./log/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - _self_
  - dataset: aihub # aihub, cnndm
  - trainer: default

model:
  base_checkpoint: klue/bert-base
  enc_num_layers: 2
  enc_intermediate_size: 2048
  enc_num_attention_heads: 8
  enc_dropout_prob: 0.1

train_checkpoint:
test_checkpoint: ./checkpoints/2025-06-23/13-42-55/epoch=4-step=1116.ckpt

engine:
  sum_size: 3
  pred_sum_size: 5
  model_checkpoint:
  freeze_base: False
  lr: 2e-3
  betas: [0.9, 0.999]
  weight_decay: 0.0
  num_warmup_steps: 10000
  save_result: True

max_seq_len: 512
batch_size: 16

log:
  project: bertext
  name: bertext_exp_1--${now:%Y-%m-%d}/${now:%H-%M-%S}
  save_dir: ./log