  
Trainer:
  accelerator: gpu
  devices: auto
  max_epochs: 5
  val_check_interval: 500
  accumulate_grad_batches: 2
  gradient_clip_val: 1.0
  log_every_n_steps: 10
  precision: 16-mixed

Callbacks:
  LearningRateMonitor:
    logging_interval: step

  EarlyStopping:
    monitor: val_rougeL
    patience: 5
    mode: max

  ModelCheckpoint:
    monitor: val_loss
    save_top_k: 3
    mode: min
    dirpath: ./checkpoints/${now:%Y-%m-%d}/${now:%H-%M-%S}


Profiler:
  SimpleProfiler:

Strategy:
  DDPStrategy:
    find_unused_parameters: true