hydra:
  run:
    dir: ./log/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - _self_
  - dataset: aihub # aihub, food
  - trainer: default

dataset:
  use_df: none  # [aihub] 0: 법률, 1: 사설, 2: 신문기사 [food] none

mode:
  model: matchsum

train_checkpoint:
test_checkpoint:

model:
  tokenizer: klue/bert-base # kor: klue/bert-base
  candidate_num: 20
  margin: 0.2

encoder:
  encoder_path: /home/food/people/hyeonjin/FoodSafetyCrawler/matchsum/BertExt/bertext_only.pt
  enc_num_layers: 2
  enc_intermediate_size: 2048
  enc_num_attention_heads: 8
  enc_dropout_prob: 0.1

max_seq_len: 512
batch_size: 4

engine:
  sum_size: 3
  pred_sum_size: 5
  candidate_num: 20
  model_checkpoint: 
  freeze_base: False
  lr: 2e-5
  betas: [0.9, 0.999]
  margin: 0.2 # gamma_2
  weight_decay: 0.0
  adam_epsilon: 1e-8
  num_warmup_steps: 500
  save_result: True

log:
  project: matchsum_food
  name: experiment_1--${now:%Y-%m-%d}/${now:%H-%M-%S}
  save_dir: ./logs
